<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Evita colision CS0118 entre el namespace "Order.API" y la clase de dominio "Order" -->
    <RootNamespace>OrderService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="9.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
